spring:
    datasource:
        url: jdbc:postgresql://10.181.10.61:5432/stations
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver
    jpa:
        show-sql: true
        hibernate.ddl-auto: create
        database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
    port: 8088
