spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/stations
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver
    jpa:
        show-sql: true
        hibernate.ddl-auto: validate
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    mvc:
        format:
            date: dd.MM.yyyy
            date-time: dd.MM.yyyy HH:mm:ss
            time: HH:mm:ss
server:
    port: 8088
